export const Pages = {
  Kit: '/kit',
  SignIn: '/',
  SignUp: '/signup',
  Dashboard: '/cabinet',
  Support: '/support',
  RequestStatus: '/request-status',
  Conditions: '/conditions',
  Overview: '/cabinet',
  Payment: '/payment',
  Services: '/services',
  Roaming: '/roaming',
  History: '/history',
  Settings: '/settings',
  Exit: '/',
  AddPackage: '/add-package',
  PayPackage: '/pay-package',
  PayResult: '/pay-result',
  AutoPay: '/auto-pay',
  SiteMap: '/sitemap',
  SupportDashboard: '/support-dashboard',
};

export const Statuses = {
  REQUEST_SENT: 'request-sent',
  INFORMATION_CHECKED: 'information-checked',
  CHANGES_SAVED: 'changes-saved',
  TRANSITION_CONFIRMED: 'transition-confirmed',
  TRANSITION_STOPPED: 'transition-stopped',
  SIM_DELIVERY: 'sim-delivery',
  SIM_DELIVERY_TODAY: 'sim-delivery-today',
};
